version: "3.7"

services:
  idb:
    image:
    hostname: influx
    deploy:
      restart_policy:
        delay: 5s
      resources:
        limits:
          cpus: "2.0"
          memory: 2000M
      update_config:
        parallelism: 1
        delay: 10s
      replicas: 1
    ports:
      - 8086:8086
    volumes:
        - "/influx:/var/lib/influxdb"

